# Generated by Django 5.2.17 on 2026-09-13 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0002_org_about_org_governance_text_org_governance_url_and_more'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(blank=True, help_text='One or two sentences for lists and the feed', max_length=300)),
                ('body', models.TextField(help_text='Markdown')),
                ('photo', models.ImageField(blank=True, upload_to='posts/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending review'), ('published', 'Published')], default='draft', max_length=12)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, help_text="Shown only if the author's profile is published", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='people.person')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='campaigns.org')),
            ],
            options={
                'ordering': ['-published_at', '-created'],
                'constraints': [models.UniqueConstraint(fields=('org', 'slug'), name='post_slug_per_org')],
            },
        ),
    ]
