# Generated by Django 5.2.17 on 2026-09-14 05:12

import campaigns.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preview_token',
            field=models.CharField(default=campaigns.models.preview_token, editable=False, max_length=24),
        ),
    ]
