# Generated by Django 5.2.17 on 2026-09-14 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_preview_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='source_url',
            field=models.URLField(blank=True, help_text='Where these words were first published (e.g. the LinkedIn post)'),
        ),
    ]
