# Generated by Django 5.2.17 on 2026-09-06 15:41

import django.db.models.deletion
import letters.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('kind', models.CharField(choices=[('open_letter', 'Open letter'), ('petition', 'Petition')], default='open_letter', max_length=12)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(help_text='Markdown: **bold**, *italic*, blank line between paragraphs, - bullets')),
                ('addressee', models.CharField(blank=True, help_text='Petitions: who it is addressed to', max_length=200)),
                ('goal', models.PositiveIntegerField(blank=True, help_text='Petitions: signature target', null=True)),
                ('theme', models.CharField(choices=[('parchment', 'Parchment')], default='parchment', max_length=12)),
                ('show_signatures', models.BooleanField(default=True)),
                ('updates_label', models.CharField(default='Keep me updated about this letter', max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending review'), ('published', 'Published')], default='draft', max_length=12)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters', to='campaigns.org')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('drawn', models.ImageField(blank=True, upload_to='signatures/')),
                ('extras', models.JSONField(blank=True, default=dict, help_text="Answers to the letter's own fields, by key")),
                ('keep_updated', models.BooleanField(default=False)),
                ('token', models.CharField(default=letters.models._token, max_length=64, unique=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirm_sent_at', models.DateTimeField(blank=True, null=True)),
                ('confirm_sends', models.PositiveSmallIntegerField(default=0)),
                ('hidden', models.BooleanField(default=False, help_text='Kept, never shown')),
                ('on_pdf', models.BooleanField(default=True)),
                ('pdf_sort', models.IntegerField(default=0, help_text='Lower comes first on the PDF')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='letters.letter')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('error', models.TextField(blank=True)),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='letters.letter')),
                ('signature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='letters.signature')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='SignatureField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Stored under this name, e.g. affiliation')),
                ('label', models.CharField(help_text='Shown to the signer, e.g. Affiliation', max_length=120)),
                ('kind', models.CharField(choices=[('short', 'Short text'), ('long', 'Paragraph'), ('checkbox', 'Checkbox')], default='short', max_length=10)),
                ('required', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=True, help_text='Shown next to the signature on the page and PDF')),
                ('sort', models.PositiveSmallIntegerField(default=0)),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='letters.letter')),
            ],
            options={
                'ordering': ['sort', 'id'],
                'unique_together': {('letter', 'key')},
            },
        ),
    ]
