# Generated by Django 5.2.17 on 2026-09-08 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='approved',
            field=models.BooleanField(default=False, help_text='Counts and is shown even without a confirmed email or drawn signature'),
        ),
        migrations.AddField(
            model_name='signature',
            name='confirm_attempts',
            field=models.PositiveSmallIntegerField(default=0, help_text='Confirmation mails tried, sent or failed'),
        ),
        migrations.AddField(
            model_name='signature',
            name='confirm_last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signature',
            name='confirm_last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='signature',
            name='confirm_next_retry_at',
            field=models.DateTimeField(blank=True, help_text='When the next retry is due; empty = none scheduled', null=True),
        ),
    ]
