# Generated by Django 5.2.17 on 2026-09-13 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0002_org_about_org_governance_text_org_governance_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, help_text='e.g. Director, Member, Mentor', max_length=200)),
                ('bio', models.TextField(blank=True, help_text="Markdown. The person's own words.")),
                ('photo', models.ImageField(blank=True, upload_to='people/')),
                ('links', models.TextField(blank=True, help_text='One URL per line (site, LinkedIn, Bluesky…)')),
                ('consent_on_record', models.BooleanField(default=False, help_text='The person agreed, in writing, to be named on this site. Required to publish.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending review'), ('published', 'Published')], default='draft', max_length=12)),
                ('sort', models.PositiveSmallIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='campaigns.org')),
                ('user', models.ForeignKey(blank=True, help_text='Login this profile belongs to, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'people',
                'ordering': ['sort', 'name'],
                'constraints': [models.UniqueConstraint(fields=('org', 'slug'), name='person_slug_per_org')],
            },
        ),
    ]
