# Generated by Django 5.2.17 on 2026-09-14 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='simpletip_receiver',
            field=models.SlugField(blank=True, help_text="SimpleTip receiver id: readers can tip this person's posts (split with the campaign)"),
        ),
    ]
