# Generated by Django 5.2.17 on 2026-08-31 22:00

import campaigns.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('organizer', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('summary', models.TextField(blank=True, help_text='Short text for listings and share cards')),
                ('story', models.TextField(blank=True, help_text="The campaign's own words. Facts only; cite sources.")),
                ('photo', models.ImageField(blank=True, upload_to='campaigns/')),
                ('source_url', models.URLField(blank=True, help_text='Where the story facts come from')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending review'), ('published', 'Published')], default='draft', max_length=12)),
                ('givebutter_campaign_id', models.CharField(blank=True, help_text='Widget ID from Givebutter dashboard → Developers → Widgets', max_length=100)),
                ('simpletip_receiver', models.SlugField(blank=True)),
                ('simpletip_api', models.URLField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('website', models.URLField(blank=True)),
                ('givebutter_account_id', models.CharField(blank=True, help_text='Account ID from Givebutter dashboard (script embed)', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('give', 'Give'), ('mentor', 'Mentor / practice English'), ('hire', 'Hire someone'), ('event', 'Host an event'), ('ama', 'Ask Me Anything'), ('subscribe', 'Get updates')], max_length=12)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('button_label', models.CharField(default='Sign up', max_length=40)),
                ('sort', models.PositiveSmallIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ctas', to='campaigns.campaign')),
            ],
            options={
                'verbose_name': 'Call to action',
                'verbose_name_plural': 'Calls to action',
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='campaigns.org'),
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(blank=True)),
                ('handled', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='campaigns.cta')),
            ],
        ),
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=campaigns.models._share_code, max_length=16, unique=True)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='campaigns.campaign')),
                ('volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('video', models.FileField(blank=True, upload_to='testimony/')),
                ('display_name', models.CharField(blank=True, help_text='Shown publicly ONLY if show_identity is on', max_length=200)),
                ('show_identity', models.BooleanField(default=False, help_text='Opt-in. Names/faces tied to funding can endanger people.')),
                ('relationship', models.CharField(blank=True, help_text="e.g. 'donor since June'", max_length=200)),
                ('linkedclaim_uri', models.URLField(blank=True, help_text='Signed LinkedClaim for this testimony')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending review'), ('published', 'Published')], default='pending', max_length=12)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='campaigns.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('text', models.TextField(help_text='Facts: receipts, counts, milestones')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending review'), ('published', 'Published')], default='draft', max_length=12)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='campaigns.campaign')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approver', models.BooleanField(default=False, help_text='May publish pending content')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteers', to='campaigns.org')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
