# Generated by Django 5.2.17 on 2026-09-13 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='about',
            field=models.TextField(blank=True, help_text='Markdown. The org in its own words; facts only.'),
        ),
        migrations.AddField(
            model_name='org',
            name='governance_text',
            field=models.TextField(blank=True, help_text="Markdown. How members govern — the director's/members' own words. Shown on the Governance page when set."),
        ),
        migrations.AddField(
            model_name='org',
            name='governance_url',
            field=models.URLField(blank=True, help_text='Where governance lives (GovKit org page on dash.workers.vc, or the workers.vc venture page). act only links to it.'),
        ),
        migrations.AddField(
            model_name='org',
            name='tagline',
            field=models.CharField(blank=True, help_text='One line under the name on the home page', max_length=200),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='volunteerprofile',
            constraint=models.UniqueConstraint(fields=('user', 'org'), name='one_profile_per_user_org'),
        ),
    ]
