# Generated by Django 5.2.17 on 2026-09-14 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_org_about_org_governance_text_org_governance_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cta',
            name='note',
            field=models.CharField(blank=True, help_text='Small line above the text, e.g. "Next: 2026-10-01 18:00 UTC"', max_length=120),
        ),
        migrations.AlterField(
            model_name='cta',
            name='kind',
            field=models.CharField(choices=[('give', 'Give'), ('mentor', 'Mentor / practice English'), ('hire', 'Hire someone'), ('event', 'Host an event'), ('ama', 'Ask Me Anything'), ('podcast', 'Podcast tie-in'), ('subscribe', 'Get updates')], max_length=12),
        ),
    ]
