# Generated by Django 5.2.17 on 2026-09-14 05:12

import campaigns.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_cta_note_alter_cta_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='preview_token',
            field=models.CharField(default=campaigns.models.preview_token, editable=False, help_text='Draft is viewable at ?preview=<token> without a login', max_length=24),
        ),
    ]
