# Generated by Django 5.2.17 on 2026-09-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaign_preview_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='claim_id',
            field=models.PositiveIntegerField(blank=True, help_text='LinkedTrust claim id (renders the badge)', null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='sign_error',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='video_url',
            field=models.URLField(blank=True, help_text='Recorded in the browser and stored by LinkedTrust'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='video',
            field=models.FileField(blank=True, help_text='Local file (fallback)', upload_to='testimony/'),
        ),
    ]
