# Generated by Django 5.2.17 on 2026-09-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_testimonial_claim_id_testimonial_sign_error_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cta',
            name='kind',
            field=models.CharField(choices=[('give', 'Give'), ('mentor', 'Mentor / practice English'), ('networking', 'Open your network'), ('hire', 'Hire someone'), ('event', 'Host an event'), ('ama', 'Ask Me Anything'), ('podcast', 'Podcast tie-in'), ('subscribe', 'Get updates')], max_length=12),
        ),
        migrations.AlterField(
            model_name='org',
            name='governance_text',
            field=models.TextField(blank=True, help_text="Markdown. How members govern, in the director's/members' own words. Shown on the Governance page when set."),
        ),
    ]
