# Generated by Django 5.2.17 on 2026-09-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_ssoidentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
