# Generated by Django 5.2.17 on 2026-09-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_response_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='givebutter_campaign_url',
            field=models.URLField(blank=True, help_text='Public Givebutter campaign URL (e.g. https://givebutter.com/your-campaign).'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='givebutter_goal_id',
            field=models.CharField(blank=True, help_text='Optional Givebutter goal/progress widget ID, shown above the donate box.', max_length=100),
        ),
        migrations.AddField(
            model_name='campaign',
            name='moderate_vouches',
            field=models.BooleanField(default=False, help_text='Hold new vouches for review before they show on the page.'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='source_uri',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
